name: Playwright Chrome Tests

# Required GitHub Secrets (go to Settings > Secrets and variables > Actions):
# QA_USERNAME - Username for QA environment
# QA_PASSWORD - Password for QA environment  
# DEV_USERNAME - Username for DEV environment
# DEV_PASSWORD - Password for DEV environment
# Optional:
# QA_BASE_URL - Base URL for QA (defaults to https://rahulshettyacademy.com)
# DEV_BASE_URL - Base URL for DEV (defaults to https://rahulshettyacademy.com)

on:
  push:
    branches: [ main, master, Github ]
  pull_request:
    branches: [ main, master, Github ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [qa, dev]
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    
    - name: Create environment file
      run: |
        if [ "${{ matrix.environment }}" = "qa" ]; then
          echo "BASE_URL=${{ secrets.QA_BASE_URL || 'https://rahulshettyacademy.com' }}" > .env.qa
          echo "USERNAME=${{ secrets.QA_USERNAME }}" >> .env.qa
          echo "PASSWORD=${{ secrets.QA_PASSWORD }}" >> .env.qa
        else
          echo "BASE_URL=${{ secrets.DEV_BASE_URL || 'https://rahulshettyacademy.com' }}" > .env.dev
          echo "USERNAME=${{ secrets.DEV_USERNAME }}" >> .env.dev
          echo "PASSWORD=${{ secrets.DEV_PASSWORD }}" >> .env.dev
        fi
    
    - name: Run Playwright tests in Chrome
      run: npx playwright test --project=${{ matrix.environment }}
      env:
        ENV: ${{ matrix.environment }}
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.environment }}
        path: playwright-report/
        retention-days: 30
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.environment }}
        path: test-results/
        retention-days: 30
